### ISSUE TITLE
can you share the sample library_inventory.erl ?

### ISSUE THREAD

**Issue by larrycai** [srijan/rebar3_dialyzer_html#3]
do u have the git repo for it?

**Comment by srijan** [comment]
Yes, it's here: [https://github.com/srijan/library_sample](https://github.com/srijan/library_sample)

(Originally published at: https://srijan.ch/notes/2024-05-17-001)

**Comment by larrycai** [comment]
good, tried with dialyzer_html, no errors.

 do you have sample with some errors like in your blog, so I can check the html result better

Thx

Below is what I did using container

```bash
$ podman run -it -v $PWD:/code -w /code erlang:25.3.2-alpine ash
/code # vi rebar.config 
/code # rebar3 compile
/code # rebar3 dialyzer
/code # rebar3 dialyzer_html
===> Fetching rebar3_dialyzer_html v0.2.0
===> Analyzing applications...
===> Compiling rebar3_dialyzer_html
===> Generating Dialyzer HTML Report
===> HTML Report written to /code/_build/default/dialyzer_report.html
```

Below lines are added into `rebar.config`

```
{plugins, [
    %% from hex
    {rebar3_dialyzer_html, "0.2.0"}
]}.
{dialyzer, [
    {warnings, [underspecs,no_undefined_callbacks, no_return]}
]}.
```

**Comment by larrycai** [comment]
anyway I found other sample, which is ok for me
